version: "3"
services:
    postgres:
        image: "postgres:latest"
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - /data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
        networks:
            - backend
    backend:
        build:
            context: .
        ports:
            - "3333:3333"
        volumes:
            - ".:/usr/backend"
            - "/usr/backend/node_modules"
        environment:
            - PORT=3333
            - DB_HOST=postgres
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - SECRET=your-secret-here
        links:
            - postgres
        depends_on:
            - postgres
        networks:
            - backend
networks:
    backend:
        driver: bridge
